### ISSUE TITLE
MIT License Violation

### ISSUE THREAD

**Issue by felicianotech** [binomads/hugo-theme-launch-page#3]
This Hugo theme is clearly a derivative of my Hugo theme I made [here](https://github.com/felicianotech/hugo-theme-lean-launch-page).

My project is licensed under the MIT license and as such, allows modifications. Great, it's flattering that you thought my project was worth modifying however you removed my copyright from the project which is a violation.

Please add my copyright properly or remove this theme from GitHub.

This has already [been reported](https://discourse.gohugo.io/t/hugo-theme-launch-page-broke-my-mit-license/8974) to the Hugo team and they have removed this theme from their theme directory.

**Comment by davidpelayo** [comment]
Hi @felicianotech.

As publicly declared via twitter and Hugo discussion platform, this was due mistake.

I've [already fixed the MIT License](https://github.com/binomads/hugo-theme-launch-page/commit/fc792841b7fa2cb38d0d5a49d8c3ba67812dab88) and [added a reference back to your repo](https://github.com/binomads/hugo-theme-launch-page/commit/c366218e7769b41ee2fdd9214188d6cd83453b27).

Thanks for notifying.
